- name: Create Release & Upload
  uses: softprops/action-gh-release@v1
  with:
    files: |
      dist/UnitFlow-Windows.exe
      dist/UnitFlow-Linux
      dist/UnitFlow-macOS
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}